New calculations for person total balance
Metatavu/time-bank-api-v2 pull request #33
Opened 2023-02-01 11:46 UTC by Kaitsuus

2023-02-01 13:20 UTC, Jdallos requested changes

2023-02-01 13:20 UTC, Jdallos commented on src/main/kotlin/fi/metatavu/timebank/api/controllers/PersonsController.kt
> +
```suggestion
```

2023-02-01 13:20 UTC, Jdallos commented on src/main/kotlin/fi/metatavu/timebank/api/controllers/PersonsController.kt
> +
Remove unnecessary empty line

2023-02-01 13:20 UTC, Jdallos commented on src/main/kotlin/fi/metatavu/timebank/api/controllers/PersonsController.kt
> +
```suggestion
```

2023-02-01 13:20 UTC, Jdallos commented on src/main/kotlin/fi/metatavu/timebank/api/controllers/PersonsController.kt
> +
Remove unnecessary empty line

2023-02-01 13:20 UTC, Jdallos commented on src/main/kotlin/fi/metatavu/timebank/api/controllers/PersonsController.kt
> +            if ( idx == 0) latestDay = day.expected
```suggestion
            if (idx == 0) latestDay = day.expected
```

2023-02-01 13:20 UTC, Jdallos commented on src/main/kotlin/fi/metatavu/timebank/api/controllers/PersonsController.kt
> +
```suggestion
```

2023-02-01 13:20 UTC, Jdallos commented on src/main/kotlin/fi/metatavu/timebank/api/controllers/PersonsController.kt
> +
Remove unnecessary empty line

2023-02-01 13:20 UTC, Jdallos commented on src/main/kotlin/fi/metatavu/timebank/api/controllers/PersonsController.kt
> +            if ( idx == 0) latestDay = day.expected
Lets discuss this latest day logic

2023-02-01 13:20 UTC, Jdallos commented on src/test/kotlin/fi/metatavu/timebank/api/test/functional/data/TestDateUtils.kt
> +        fun getThirtyDaysAgoFourthWeek(): List<LocalDate> {
This function isn't used anywhere, so is it needed?

2023-02-01 13:20 UTC, Jdallos commented on src/test/kotlin/fi/metatavu/timebank/api/test/functional/tests/DailyEntriesTest.kt
> -
A line break here between the vals and the assertions was perhaps helpful for readability

2023-02-01 13:20 UTC, Jdallos commented on src/test/kotlin/fi/metatavu/timebank/api/test/functional/tests/PersonsTest.kt
> +            assertTrue(personTotalTimes.all { it.balance <= 0 } )
Lets also discuss this

2023-02-01 13:20 UTC, Jdallos commented on src/test/kotlin/fi/metatavu/timebank/api/test/functional/tests/PersonsTest.kt
> +
```suggestion
```

2023-02-01 13:20 UTC, Jdallos commented on src/test/kotlin/fi/metatavu/timebank/api/test/functional/tests/PersonsTest.kt
> +
Don't need an empty line between two closing brackets.

2023-02-01 13:20 UTC, Jdallos commented on src/test/kotlin/fi/metatavu/timebank/api/test/functional/tests/PersonsTest.kt
> +            println(expectedWeeks)
We generally try to avoid leaving logs, is there a specific reason for these print lines?

2023-02-01 13:20 UTC, Jdallos commented on src/test/kotlin/fi/metatavu/timebank/api/test/functional/tests/PersonsTest.kt
> +                assertTrue(it.balance <= 0)
As in a previous comment, lets discuss so you can explain to me whats going on here with this assertion, it seems suspiciously vague.

2023-02-06 13:17 UTC, Jdallos commented on src/test/kotlin/fi/metatavu/timebank/api/test/functional/data/TestTimeEntriesData.kt
> +                        id = 17,
Fix indentation

2023-02-06 13:35 UTC, VeikkoVilpponen commented on src/test/kotlin/fi/metatavu/timebank/api/test/functional/tests/PersonsTest.kt
> +            assertTrue(personTotalTimes.all { it.balance <= 0 } )
we will investigate.

2023-02-17 06:37 UTC, closed without merging