Feature 7 testing
Metatavu/time-bank-api-v2 pull request #9
Opened 2022-06-28 09:14 UTC by villejuutila

Both, JVM and Native tests implemented. 

Also contains other changes related to for example building a native image.

New TimeEntryAPI and TimeEntryController was suggested by @jarinykanen.
Mainly to be able to clean resources persisted by tests, since earlier there was no endpoint for deleting persisted entries.
Also it was considered future proofing since at some point we probably want to be able to delete persisted entries.

2022-06-28 12:02 UTC, anttileppa commented on src/test/kotlin/fi/metatavu/timebank/api/test/functional/tests/SynchronizeTest.kt
> +            val synchronized = testBuilder.manager.synchronization.synchronizeEntries()
Is it possible that this test leaves from garbage behind?

2022-07-25 06:40 UTC, jarinykanen requested changes

2022-07-25 06:40 UTC, jarinykanen commented on src/main/kotlin/fi/metatavu/timebank/api/forecast/models/ForecastPerson.kt
> +
```suggestion
```

2022-07-25 06:40 UTC, jarinykanen commented on src/main/kotlin/fi/metatavu/timebank/api/persistence/model/TimeEntry.kt
> +                updatedAt == timeEntry.updatedAt
```suggestion
        return forecastId == timeEntry.forecastId &&
            person == timeEntry.person &&
            internalTime == timeEntry.internalTime &&
            projectTime == timeEntry.projectTime &&
            date == timeEntry.date &&
            createdAt == timeEntry.createdAt &&
            updatedAt == timeEntry.updatedAt
```

2022-07-25 06:40 UTC, jarinykanen commented on src/native-test/kotlin/fi/metatavu/timebank/api/test/NativeSystemTestIT.kt
> +
```suggestion
```

2022-07-25 06:40 UTC, jarinykanen commented on src/test/kotlin/fi/metatavu/timebank/api/test/functional/data/TestData.kt
> +        private fun createForecastTimeEntryResponse(
Add docs

2022-07-25 06:40 UTC, jarinykanen commented on src/test/kotlin/fi/metatavu/timebank/api/test/functional/data/TestPersonsData.kt
> +        private fun createTestPerson(
Add docs

2022-07-25 06:40 UTC, jarinykanen commented on src/test/kotlin/fi/metatavu/timebank/api/test/functional/data/TestTimeEntriesData.kt
> +        fun getForecastTimeEntries(): List<ForecastTimeEntry> {
Add docs, check all methods

2022-07-25 06:40 UTC, jarinykanen commented on src/test/kotlin/fi/metatavu/timebank/api/test/functional/tests/PersonsTest.kt
> +
```suggestion

```

2022-07-25 06:52 UTC, villejuutila commented on src/test/kotlin/fi/metatavu/timebank/api/test/functional/tests/AbstractTest.kt
> +                    .url("http://localhost:8082/__admin/scenarios/reset")
This particular variable is a config property overridden by our WireMock instance. 
For some strange reason config properties overridden by services other than Quarkus DevServices or Testcontainers do not get into the context of these test classes IN NATIVE MODE. In JVM mode it works just fine.
As of now, replaced this particular line with a variable, where the value is hard-coded tho.

2022-07-25 06:52 UTC, villejuutila commented on src/test/kotlin/fi/metatavu/timebank/api/test/functional/tests/AbstractTest.kt
> +                        .url("http://localhost:8082/__admin/scenarios/$scenario/state")
This particular variable is a config property overridden by our WireMock instance. 
For some strange reason config properties overridden by services other than Quarkus DevServices or Testcontainers do not get into the context of these test classes IN NATIVE MODE. In JVM mode it works just fine.
As of now, replaced this particular line with a variable, where the value is hard-coded tho.

2022-07-25 07:30 UTC, jarinykanen approved these changes

2022-07-25 07:30 UTC, merged